/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nhom9.AgencyStoreManager;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Hashtable;
import java.util.Locale;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author honkaiwaifu
 */
public class BillNotes extends javax.swing.JFrame {
    Connection con = NewConnection.getConnection();
    PreparedStatement ps, ps1, ps2;
    ResultSet rs, rs1, rs2;
    DefaultTableModel d, d1;
    /**
     * Creates new form PHIEUXUATHANG
     */
    public BillNotes() {
        initComponents();
        phieuxuat_load();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        MaPhieuXuatField = new javax.swing.JTextField();
        MaDaiLyList = new javax.swing.JComboBox<>();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PHIEUXUATTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        CHITIETTable = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        DatePicker = new org.jdesktop.swingx.JXDatePicker();
        jLabel5 = new javax.swing.JLabel();
        NameField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(230, 34, 34));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PHIẾU XUẤT HÀNG");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Mã phiếu xuất");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Mã đại lý");

        MaDaiLyList.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MaDaiLyList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chọn mã đại lý" }));
        MaDaiLyList.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                MaDaiLyListPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        PHIEUXUATTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã phiếu xuất", "Mã đại lý", "Tổng tiền", "Ngày lập phiếu"
            }
        ));
        PHIEUXUATTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PHIEUXUATTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(PHIEUXUATTable);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Lưu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Sửa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Làm mới");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("Xoá");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setText("Thoát");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton9.setText("Tổng");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Các phiếu xuất", jPanel2);

        CHITIETTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã mặt hàng", "Tên mặt hàng", "Đơn vị tính", "Số lượng", "Đơn giá", "Thành tiền"
            }
        ));
        jScrollPane4.setViewportView(CHITIETTable);

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton6.setText("Xuất ");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton7.setText("Chi Tiết");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton8.setText("Cập nhật");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton10.setText("Thoát");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton6)
                    .addComponent(jButton8)
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26))
        );

        jTabbedPane1.addTab("Chi tiết phiếu xuất", jPanel3);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Ngày lập phiếu");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Tên đại lý");

        NameField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(MaPhieuXuatField)
                            .addComponent(MaDaiLyList, 0, 132, Short.MAX_VALUE))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DatePicker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NameField)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MaPhieuXuatField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NameField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(MaDaiLyList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    //bảng các phiếu xuất
    //lưu phiếu xuất
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String madl, maphieu, date; 
       madl = MaDaiLyList.getSelectedItem().toString();
       maphieu = MaPhieuXuatField.getText();
       SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
       date = sdf.format(DatePicker.getDate());
       if      (madl.equals("")   || 
                maphieu.equals("")   || 
                date.equals("")  ) {
            JOptionPane.showMessageDialog(this,"Vui lòng nhập đầy đủ thông tin",
                "Thông báo",JOptionPane.ERROR_MESSAGE);
        
        } else {           
            try {
                ps = con.prepareStatement("INSERT PHIEUXUATHANG(MaPhieuXuat, MaDaiLy, NgayLapPhieu) values(?,?,?) ");
                ps.setString(1,maphieu);
                ps.setString(2,madl);
                ps.setString(3,date);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this,"Lưu phiếu thành công","Đại lý",JOptionPane.INFORMATION_MESSAGE);
                /*DLTypeList.removeAllItems();*/
                
                
                phieuxuat_load();
            } catch (SQLException ex) {
                Logger.getLogger(BillNotes.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    //chọn phiếu trên bảng
    private void PHIEUXUATTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PHIEUXUATTableMouseClicked
        d = (DefaultTableModel)PHIEUXUATTable.getModel();
        int selectIndex = PHIEUXUATTable.getSelectedRow();  
        MaPhieuXuatField.setText(d.getValueAt(selectIndex, 0).toString());
        MaDaiLyList.setSelectedItem(d.getValueAt(selectIndex, 1).toString());
        String madl = MaDaiLyList.getSelectedItem().toString();
        try {
            ps = con.prepareStatement("SELECT TenDaiLy FROM DAILY WHERE MaDaiLy = ? ");
            ps.setString(1, madl);
            rs = ps.executeQuery();
            if (rs.next()) {
                String name = rs.getString("TenDaiLy");
                NameField.setText(String.valueOf(name));
            }
        } catch (SQLException ex) {
            Logger.getLogger(BillNotes.class.getName()).log(Level.SEVERE, null, ex);
        }
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");       
        try {
            DatePicker.setDate(sdf.parse(d.getValueAt(selectIndex, 3).toString()));
        } catch (ParseException ex) {
            Logger.getLogger(BillNotes.class.getName()).log(Level.SEVERE, null, ex);
        }
           
        MaPhieuXuatField.setEnabled(false);
        jButton1.setEnabled(false);
    }//GEN-LAST:event_PHIEUXUATTableMouseClicked
    //sửa phiếu xuất bảng
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       String madl, maphieu, date; 
       madl = MaDaiLyList.getSelectedItem().toString();
       SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
       date = sdf.format(DatePicker.getDate());
            try {
                d = (DefaultTableModel)PHIEUXUATTable.getModel();
                int selectIndex = PHIEUXUATTable.getSelectedRow(); 
                maphieu = d.getValueAt(selectIndex, 0).toString();
                ps = con.prepareStatement("UPDATE PHIEUXUATHANG SET MaDaiLy = ?, NgayLapPhieu = ? "
                        + "WHERE MaPhieuXuat = ?");
                ps.setString(1,madl);       
                ps.setString(2,date);
                ps.setString(3,maphieu);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this,"Sửa phiếu thành công","Đại lý",JOptionPane.INFORMATION_MESSAGE);
                /*DLTypeList.removeAllItems();*/
                
                jButton1.setEnabled(true);
                phieuxuat_load();
            } catch (SQLException ex) {
                Logger.getLogger(InforAgency.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jButton2ActionPerformed
    //làm mới
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jButton1.setEnabled(true);
        MaPhieuXuatField.setEnabled(true);
        NameField.setText("");
        MaPhieuXuatField.setText("");       
        phieuxuat_load();
        MaDaiLyList.setSelectedIndex(0);
    }//GEN-LAST:event_jButton3ActionPerformed
    //xoá phiếu xuất
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
                d = (DefaultTableModel)PHIEUXUATTable.getModel();
                int selectIndex = PHIEUXUATTable.getSelectedRow(); 
                String maphieu = d.getValueAt(selectIndex, 0).toString();
                ps = con.prepareStatement("DELETE FROM PHIEUXUATHANG WHERE MaPhieuXuat = ?");
                ps.setString(1,maphieu);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this,"Xoá phiếu thành công","Đại lý",JOptionPane.INFORMATION_MESSAGE);
                /*DLTypeList.removeAllItems();*/
                
                jButton1.setEnabled(true);
                phieuxuat_load();
            } catch (SQLException ex) {
                Logger.getLogger(InforAgency.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jButton4ActionPerformed
    //thoát form
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.dispose();
       
    }//GEN-LAST:event_jButton5ActionPerformed
    //bảng các phiếu xuất
    
    
    //Hiện tên đại lý khi chọn mã
    private void MaDaiLyListPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_MaDaiLyListPopupMenuWillBecomeInvisible
        String madl = MaDaiLyList.getSelectedItem().toString();
        try {
            ps = con.prepareStatement("SELECT TenDaiLy FROM DAILY WHERE MaDaiLy = ? ");
            ps.setString(1, madl);
            rs = ps.executeQuery();
            if (rs.next()) {
                String name = rs.getString("TenDaiLy");
                NameField.setText(String.valueOf(name));
            }
        } catch (SQLException ex) {
            Logger.getLogger(BillNotes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_MaDaiLyListPopupMenuWillBecomeInvisible

    
    
    //bảng chi tiết xuất hàng
    //xuất hàng
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       XuatHoaDon();
    }//GEN-LAST:event_jButton6ActionPerformed
    //chi tiết đơn hàng
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
         ShipmentDetails xh = new ShipmentDetails();
         xh.setVisible(true);
         xh.setResizable(false);
         xh.pack();
         xh.setLocationRelativeTo(null);
         xh.setTitle("Phiếu xuất hàng");
    }//GEN-LAST:event_jButton7ActionPerformed
    //cập nhật chi tiết xuất hàng sau khi điền từ form  chi tiết xuất hàng
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        xuathang_load();
    }//GEN-LAST:event_jButton8ActionPerformed
    //thoát form
    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        this.dispose();
        
    }//GEN-LAST:event_jButton10ActionPerformed
    //hàm xuất hoá đơn
    public void XuatHoaDon() {
       String madl, maphieu, date; 
       madl = MaDaiLyList.getSelectedItem().toString();
       maphieu = MaPhieuXuatField.getText();
        try {   
            Hashtable map = new Hashtable();
            JasperReport report = JasperCompileManager.compileReport("C:\\Users\\ngoth\\OneDrive\\Documents\\NetBeansProjects\\Nhom 9\\src\\report\\PHIEUXUATHANG.jrxml");
            
            map.put("MaDL", madl);
            map.put("MaPX", maphieu);
            
            JasperPrint p = JasperFillManager.fillReport(report, map, con);
            JasperViewer jReportsViewer = new JasperViewer(p, false);
            jReportsViewer.setFitWidthZoomRatio();
            jReportsViewer.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(BillNotes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    
        //tổng tiền từ phiếu xuất
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
       xuathang_load();
       int sum = 0;
       for (int i = 0; i < CHITIETTable.getRowCount(); i++) {
           sum = sum + Integer.parseInt(CHITIETTable.getValueAt(i, 5).toString());
       }
       String total = Integer.toString(sum);
       try {
                d = (DefaultTableModel)PHIEUXUATTable.getModel();
                int selectIndex = PHIEUXUATTable.getSelectedRow(); 
                String maphieu = d.getValueAt(selectIndex, 0).toString();
                ps = con.prepareStatement("UPDATE PHIEUXUATHANG SET TongTien = ? "
                        + "WHERE MaPhieuXuat = ?");
                ps.setString(1,total);       
                ps.setString(2,maphieu);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this,"Sửa phiếu thành công","Đại lý",JOptionPane.INFORMATION_MESSAGE);
                /*DLTypeList.removeAllItems();*/
                
                jButton1.setEnabled(true);
                phieuxuat_load();
            } catch (SQLException ex) {
                Logger.getLogger(InforAgency.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jButton9ActionPerformed
    
    
    
    
    
   public void phieuxuat_load() { //cho bảng phiếu xuất hàng
        int c;
        NameField.setEditable(false);
        MaDaiLyList.removeAllItems();
        MaDaiLyList.addItem("Chọn mã đại lý");
        //danh sách các mã đại lý
        try {
            ps = con.prepareStatement("SELECT MaDaiLy FROM DaiLy");
            rs = ps.executeQuery();
            while (rs.next()) {
               String maDaiLy = rs.getString("MaDaiLy");
               MaDaiLyList.addItem(maDaiLy);
            }
        } catch (SQLException ex) {
            Logger.getLogger(BillNotes.class.getName()).log(Level.SEVERE, null, ex);
        }
        //bảng các phiếu xuất
        try {           
            ps1 = con.prepareStatement("SELECT * FROM PHIEUXUATHANG ");
            rs1 = ps1.executeQuery();
            
            ResultSetMetaData rad = rs1.getMetaData();
            c = rad.getColumnCount();
            
            d = (DefaultTableModel)PHIEUXUATTable.getModel();
            d.setRowCount(0);
            
            while (rs1.next()) {
                Vector v2 = new Vector();
                for (int i = 1; i <= c; i++) {
                    v2.add(rs1.getString("MaPhieuXuat"));
                    v2.add(rs1.getString("MaDaiLy"));
                    v2.add(rs1.getString("TongTien"));
                    v2.add(rs1.getString("NgayLapPhieu"));                    
                }
                d.addRow(v2);
            }
             d.fireTableDataChanged();
            
        } catch (SQLException ex) {
            Logger.getLogger(BillNotes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void xuathang_load() { //load từ chi tiết xuất hàng
        int c1;
        String maphieu = MaPhieuXuatField.getText();
        try {           
            ps2 = con.prepareStatement("SELECT MATHANG.MaMathang, MATHANG.TenMatHang, DonViTinh, SoLuong, MATHANG.DonGia, ThanhTien FROM CHITIETXUATHANG, MATHANG  "
                    + "WHERE MaPhieuXuat = ? AND CHITIETXUATHANG.MaMatHang = MATHANG.MaMatHang");
            ps2.setString(1, maphieu);
            rs2 = ps2.executeQuery();
            
            ResultSetMetaData rad = rs2.getMetaData();
            c1 = rad.getColumnCount();
            
            d1 = (DefaultTableModel)CHITIETTable.getModel();
            d1.setRowCount(0);
            
            while (rs2.next()) {
                Vector v2 = new Vector();
                for (int i = 1; i <= c1; i++) {
                    v2.add(rs2.getString("MaMatHang"));
                    v2.add(rs2.getString("TenMatHang"));
                    v2.add(rs2.getString("DonViTinh"));
                    v2.add(rs2.getString("SoLuong"));
                    v2.add(rs2.getString("DonGia"));
                    v2.add(rs2.getString("ThanhTien"));             
                }
                d1.addRow(v2);
            }
             d1.fireTableDataChanged();
            
        } catch (SQLException ex) {
            Logger.getLogger(InforAgency.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillNotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillNotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillNotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillNotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BillNotes px = new BillNotes();
                px.setVisible(true);
                px.setResizable(false);
                px.setTitle("Phiếu xuất hàng");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable CHITIETTable;
    private org.jdesktop.swingx.JXDatePicker DatePicker;
    private javax.swing.JComboBox<String> MaDaiLyList;
    public static javax.swing.JTextField MaPhieuXuatField;
    private javax.swing.JTextField NameField;
    private javax.swing.JTable PHIEUXUATTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
