/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nhom9.AgencyStoreManager;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSetMetaData;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Vector;
import java.util.regex.Pattern;
import net.proteanit.sql.DbUtils;


/**
 *
 * @author honkaiwaifu
 */
public class InforAgency extends javax.swing.JFrame {
    Connection con = NewConnection.getConnection();
    PreparedStatement ps, ps1, ps2, ps3, ps4;
    ResultSet rs, rs1, rs2;
    DefaultTableModel d;
    /**
     * Creates new form DAILYDOC
     */
    public InforAgency() {
        initComponents();
        User_load();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        MaDaiLyField = new javax.swing.JTextField();
        DaiLyField = new javax.swing.JTextField();
        AddrField = new javax.swing.JTextField();
        QuanList = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TelField = new javax.swing.JTextField();
        EmailField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        DAILYTable = new javax.swing.JTable();
        TienNoField = new javax.swing.JTextField();
        DLTypeList = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        DatePicker = new org.jdesktop.swingx.JXDatePicker();
        SearchField = new javax.swing.JTextField();
        Choose01 = new javax.swing.JRadioButton();
        Choose02 = new javax.swing.JRadioButton();
        Choose03 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(230, 34, 34));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HỒ SƠ ĐẠI LÝ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Mã đại lý");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Tên đại lý");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Địa chỉ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Quận");

        QuanList.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        QuanList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chọn quận....", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Điện thoại");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Email");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Ngày tiếp nhận");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Tiền nợ");

        DAILYTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã đại lý", "Tên đại lý", "Loại", "Địa chỉ", "Quận", "Điện thoại", "Email", "Ngày tiếp nhận", "Tiền nợ"
            }
        ));
        DAILYTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DAILYTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(DAILYTable);

        DLTypeList.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DLTypeList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Loại" }));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Lưu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Sửa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Xoá");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setText("Làm mới");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setText("Tìm kiếm");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setText("Thoát");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("Loại");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        Choose01.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Choose01.setText("Theo mã đại lý");

        Choose02.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Choose02.setText("Theo tên đại lý");

        Choose03.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Choose03.setText("Theo loại");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(jButton5)
                        .addGap(66, 66, 66)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 38, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(QuanList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AddrField, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DaiLyField, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(MaDaiLyField, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DLTypeList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(76, 76, 76)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(14, 14, 14)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(EmailField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(TelField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TienNoField)
                    .addComponent(DatePicker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(SearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(Choose01)
                        .addGap(10, 10, 10)
                        .addComponent(Choose02)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Choose03)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DLTypeList, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(MaDaiLyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(TelField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4)))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(DaiLyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(EmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(AddrField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(TienNoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(QuanList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(DatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Choose01)
                        .addComponent(Choose02)
                        .addComponent(Choose03))
                    .addComponent(SearchField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    //Load bảng từ SQL Server
    public void User_load() {
        int c;
        DLTypeList.setSelectedIndex(0);
        QuanList.setSelectedIndex(0);
        DLTypeList.removeAllItems();
        DLTypeList.addItem("Loại");

        //danh sach loại đại lý
        try {
            ps2 = con.prepareStatement("SELECT Loai FROM LOAIDAILY");
            rs1 = ps2.executeQuery();
            while (rs1.next()) {
               String type = rs1.getString("Loai");
               DLTypeList.addItem(type);
            }
        } catch (SQLException ex) {
            Logger.getLogger(InforAgency.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            ps1 = con.prepareStatement("SELECT MaDaiLy, TenDaiLy, LOAIDAILY.Loai, DiaChi, Quan, DienThoai, Email, NgayTiepNhan, TienNo FROM DAILY, LOAIDAILY WHERE DAILY.Loai = LOAIDAILY.Loai");
            rs = ps1.executeQuery();
            
            ResultSetMetaData rad = rs.getMetaData();
            c = rad.getColumnCount();
            
            d = (DefaultTableModel)DAILYTable.getModel();
            d.setRowCount(0);
            
            while (rs.next()) {
                Vector v2 = new Vector();
                for (int i = 1; i <= c; i++) {
                    v2.add(rs.getString("MaDaiLy"));
                    v2.add(rs.getString("TenDaiLy"));
                    v2.add(rs.getString("Loai"));
                    v2.add(rs.getString("DiaChi"));
                    v2.add(rs.getString("Quan"));
                    v2.add(rs.getString("DienThoai"));
                    v2.add(rs.getString("Email"));
                    v2.add(rs.getString("NgayTiepNhan"));
                    v2.add(rs.getString("TienNo"));
                    
                }
                d.addRow(v2);
            }
             d.fireTableDataChanged();
        } catch (SQLException ex) {
            Logger.getLogger(InforAgency.class.getName()).log(Level.SEVERE, null, ex);
        }
                                                                                        
                
    }
    public void clearchoose() {
        Choose01.setSelected(false);
        Choose02.setSelected(false);
        Choose03.setSelected(false);
    }
    //hàm kiểm tra email nhập vào có tên miền tồn tại không?
    public static String email_Validation (String email) {
        String email_Pattern = "^[a-zA-Z0-9]+[@]{1}+[a-zA-Z0-9]+[.]{1}+[a-zA-Z0-9]+$";
        Pattern pattern = Pattern.compile(email_Pattern);
        if (pattern.matcher(email).matches()) {
            return "Vaild";
        } else {
            return "Invaild";
        }
    }
    
    //thêm đại lý
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:      
        String madaily, type, ten, addr, quan, tel, email, date, tienno;
        madaily = MaDaiLyField.getText();
        type = DLTypeList.getSelectedItem().toString();
        ten = DaiLyField.getText();
        addr = AddrField.getText();
        quan = QuanList.getSelectedItem().toString();
        tel = TelField.getText();
        email = EmailField.getText();
        String status = email_Validation(email);
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        date = sdf.format(DatePicker.getDate());
        tienno = TienNoField.getText();
        if (madaily.equals("")   || 
                ten.equals("")   || 
                addr.equals("")  ||
                tel.equals("")   ||
                email.equals("") ||
                date.equals("")  ||
                type.toString().equals("Loại")  || 
                tienno.equals("") ) {
            JOptionPane.showMessageDialog(this,"Vui lòng nhập đầy đủ thông tin",
                "Thông báo",JOptionPane.ERROR_MESSAGE);
        
        } else if (status.equals("Vaild")) {           
            try {
                ps = con.prepareStatement("SELECT * FROM TOCHUCDAILY");
                rs = ps.executeQuery();
                if (rs.next()) {
                    int toida = Integer.parseInt(rs.getString("SoDaiLyToiDa"));

                    ps1 = con.prepareStatement("select COUNT(Loai) AS XUATHIEN from DAILY WHERE Loai = ? ");
                    ps1.setString(1, type);
                    rs1 = ps1.executeQuery();
                    if (rs1.next()) {
                    int defcount = rs1.getInt("XUATHIEN");
                
                    if (toida > defcount) {
                        ps2 = con.prepareStatement("INSERT INTO DAILY(MaDaiLy, TenDaiLy, Loai, DiaChi, Quan, DienThoai, Email, NgayTiepNhan, TienNo) values(?,?,?,?,?,?,?,?,?) ");
                        ps2.setString(1,madaily);
                        ps2.setString(2,ten);
                        ps2.setString(3,type);
                        ps2.setString(4,addr);
                        ps2.setString(5,quan);
                        ps2.setString(6,tel);
                        ps2.setString(7,email);
                        ps2.setString(8,date);
                        ps2.setString(9,tienno);
                        ps2.executeUpdate();
                        JOptionPane.showMessageDialog(this,"Thêm đại lý thành công","Đại lý",JOptionPane.INFORMATION_MESSAGE);
                        /*DLTypeList.removeAllItems();*/

                        MaDaiLyField.setText("");
                        DaiLyField.setText("");
                        DLTypeList.setSelectedIndex(0);
                        AddrField.setText("");
                        QuanList.setSelectedIndex(0);
                        TelField.setText("");
                        EmailField.setText("");
                        TienNoField.setText("");
                        
                        User_load();
                        } else {
                            JOptionPane.showMessageDialog(this,"Số đại lý vượt tối đa!","Đại lý",JOptionPane.ERROR_MESSAGE);
                        }
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(InforAgency.class.getName()).log(Level.SEVERE, null, ex);
            }
           } else {
          JOptionPane.showMessageDialog(this,"Email không tồn tại!",
                "Thông báo",JOptionPane.ERROR_MESSAGE); 
        }
       
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void DAILYTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DAILYTableMouseClicked
        d = (DefaultTableModel)DAILYTable.getModel();
        int selectIndex = DAILYTable.getSelectedRow();        
        MaDaiLyField.setText(d.getValueAt(selectIndex, 0).toString());
        DaiLyField.setText(d.getValueAt(selectIndex, 1).toString());
        DLTypeList.setSelectedItem(d.getValueAt(selectIndex, 2).toString());
        AddrField.setText(d.getValueAt(selectIndex, 3).toString());
        QuanList.setSelectedItem(d.getValueAt(selectIndex, 4).toString());
        TelField.setText(d.getValueAt(selectIndex, 5).toString());
        EmailField.setText(d.getValueAt(selectIndex, 6).toString());
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");       
        try {
            DatePicker.setDate(sdf.parse(d.getValueAt(selectIndex, 7).toString()));
        } catch (ParseException ex) {
            Logger.getLogger(InforAgency.class.getName()).log(Level.SEVERE, null, ex);
        }
        TienNoField.setText(d.getValueAt(selectIndex, 8).toString());       
        MaDaiLyField.setEnabled(false);
        jButton1.setEnabled(false);
    }//GEN-LAST:event_DAILYTableMouseClicked
    //sửa bản ghi
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String madaily, type, ten, addr, quan, tel, email, date, tienno;
        type = DLTypeList.getSelectedItem().toString();
        ten = DaiLyField.getText();
        addr = AddrField.getText();
        quan = QuanList.getSelectedItem().toString();
        tel = TelField.getText();
        email = EmailField.getText(); 
        String status = email_Validation(email);
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        date = sdf.format(DatePicker.getDate());
        tienno = TienNoField.getText(); 
        if (status.equals("Vaild")) {
        try {
                ps = con.prepareStatement("SELECT * FROM TOCHUCDAILY");
                rs = ps.executeQuery();
                if (rs.next()) {
                    int toida = Integer.parseInt(rs.getString("SoDaiLyToiDa"));

                    ps1 = con.prepareStatement("select COUNT(Loai) AS XUATHIEN from DAILY WHERE Loai = ? ");
                    ps1.setString(1, type);
                    rs1 = ps1.executeQuery();
                    if (rs1.next()) {
                    int defcount = rs1.getInt("XUATHIEN");
                
                    if (toida > defcount) {
                            d = (DefaultTableModel)DAILYTable.getModel();
                            int selectIndex = DAILYTable.getSelectedRow();
                             madaily = d.getValueAt(selectIndex, 0).toString();
                            ps2 = con.prepareStatement("UPDATE DAILY SET TenDaiLy = ?, Loai = ?, DiaChi = ?, Quan = ?, DienThoai = ?, Email = ?, NgayTiepNhan = ?, TienNo = ? "
                            + "WHERE MaDaiLy = ?");
                            
                            ps2.setString(1,ten);
                            ps2.setString(2,type);
                            ps2.setString(3,addr);
                            ps2.setString(4,quan);
                            ps2.setString(5,tel);
                            ps2.setString(6,email);
                            ps2.setString(7,date);
                            ps2.setString(8,tienno);
                            ps2.setString(9,madaily);
                            
                            ps2.executeUpdate();
                            JOptionPane.showMessageDialog(this,"Sửa đại lý thành công","Đại lý",JOptionPane.INFORMATION_MESSAGE);
                            /*DLTypeList.removeAllItems();*/

                            MaDaiLyField.setText("");
                            DaiLyField.setText("");
                            DLTypeList.setSelectedIndex(0);
                            AddrField.setText("");
                            QuanList.setSelectedIndex(0);
                            TelField.setText("");
                            EmailField.setText("");
                            TienNoField.setText("");

                            User_load();
                            } else {
                                JOptionPane.showMessageDialog(this,"Số đại lý vượt tối đa!","Đại lý",JOptionPane.ERROR_MESSAGE);
                            }
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(InforAgency.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this,"Email không tồn tại!",
                "Thông báo",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    //làm mới
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
            jButton1.setEnabled(true);
            MaDaiLyField.setEnabled(true);           
            MaDaiLyField.setText("");
            DaiLyField.setText("");
            AddrField.setText("");
            TelField.setText("");
            EmailField.setText("");
            TienNoField.setText("");
            SearchField.setText("");
            
            DLTypeList.setSelectedIndex(0);
            QuanList.setSelectedIndex(0);
            clearchoose();
            User_load();
    }//GEN-LAST:event_jButton5ActionPerformed
    //xoá đại lý
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         try {
            d = (DefaultTableModel)DAILYTable.getModel();
            int selectIndex = DAILYTable.getSelectedRow();
             String madaily = d.getValueAt(selectIndex, 0).toString();
            ps = con.prepareStatement("delete FROM DAILY WHERE MaDaiLy = ? \n" +
                                      "delete FROM DOANHSO WHERE MaDaiLy = ? \n" +
                                      "delete FROM CONGNO WHERE MaDaiLy = ? \n" +
                                      "delete FROM PHIEUTHUTIEN WHERE MaDaiLy = ? \n" +
                                      "delete FROM PHIEUXUATHANG WHERE MaDaiLy = ? ");
                              
            ps.setString(1,madaily); 
            ps.setString(2,madaily);
            ps.setString(3,madaily);
            ps.setString(4,madaily);
            ps.setString(5,madaily);
            ps.executeUpdate();
            
            JOptionPane.showMessageDialog(this,"Xoá đại lý thành công!","Đại lý",JOptionPane.INFORMATION_MESSAGE);  
            /*DLTypeList.removeAllItems();*/
            jButton1.setEnabled(true);
            MaDaiLyField.setEnabled(true);
            
            MaDaiLyField.setText("");
            DaiLyField.setText("");
            AddrField.setText("");
            TelField.setText("");
            EmailField.setText("");
            TienNoField.setText("");
            
            DLTypeList.setSelectedIndex(0);
            QuanList.setSelectedIndex(0);
            User_load();
            } catch (SQLException ex) {
                Logger.getLogger(InforAgency.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jButton3ActionPerformed
    //Tìm kiếm bản ghi
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String search = SearchField.getText();
        try {
            if (Choose01.isSelected()) {           
                ps = con.prepareStatement("SELECT * FROM DAILY WHERE MaDaiLy = ?");      
                ps.setString(1,search);
                rs=ps.executeQuery();                
                DAILYTable.setModel(DbUtils.resultSetToTableModel(rs));
            } else if (Choose02.isSelected()) {
                ps1 = con.prepareStatement("SELECT * FROM DAILY WHERE TenDaiLy = ?");      
                ps1.setString(1,search);
                rs1=ps1.executeQuery();                
                DAILYTable.setModel(DbUtils.resultSetToTableModel(rs1));
            } else if (Choose03.isSelected()) {
                ps2 = con.prepareStatement("SELECT * FROM DAILY WHERE Loai = ?");      
                ps2.setString(1,search);
                rs2=ps2.executeQuery();                
                DAILYTable.setModel(DbUtils.resultSetToTableModel(rs2));
            } else {
                JOptionPane.showMessageDialog(this,"Chưa chọn loại tìm kiếm","Tìm kiếm", JOptionPane.ERROR_MESSAGE);
            }
           
            } catch (SQLException ex) {
                Logger.getLogger(InforAgency.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
    }//GEN-LAST:event_jButton7ActionPerformed
    //thêm loại đại lý
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        AddAgencyTypes addtype = new AddAgencyTypes();
        addtype.setVisible(true);
        addtype.setResizable(false);
        addtype.pack();
        addtype.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InforAgency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InforAgency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InforAgency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InforAgency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InforAgency dl = new InforAgency();
                dl.setVisible(true);
                dl.setResizable(false);
                dl.setTitle("Hồ sơ đại lý");
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddrField;
    private javax.swing.JRadioButton Choose01;
    private javax.swing.JRadioButton Choose02;
    private javax.swing.JRadioButton Choose03;
    private javax.swing.JTable DAILYTable;
    private javax.swing.JComboBox<String> DLTypeList;
    private javax.swing.JTextField DaiLyField;
    private org.jdesktop.swingx.JXDatePicker DatePicker;
    private javax.swing.JTextField EmailField;
    private javax.swing.JTextField MaDaiLyField;
    private javax.swing.JComboBox<String> QuanList;
    private javax.swing.JTextField SearchField;
    private javax.swing.JTextField TelField;
    private javax.swing.JTextField TienNoField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
