/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nhom9.quanlidaily;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author honkaiwaifu
 */
public class ChiTietXuatHang extends javax.swing.JFrame {
    Connection con = NewConnection.getConnection();
    PreparedStatement ps, ps1, ps2;
    ResultSet rs, rs1, rs2;
    DefaultTableModel d;
    /**
     * Creates new form ThuTien
     */
    public ChiTietXuatHang() {
        initComponents();
        User_load();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        MaPhieuXuatField = new javax.swing.JTextField();
        SLField = new javax.swing.JTextField();
        TotalField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        XUATHANGTable = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        DonViField = new javax.swing.JTextField();
        PriceField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        MaMHList = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(230, 34, 34));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("CHI TIẾT XUẤT HÀNG");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Mã phiếu xuất");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Mã mặt hàng");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Số lượng");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Thành tiền");

        SLField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SLFieldKeyReleased(evt);
            }
        });

        XUATHANGTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã phiếu xuất", "Mã mặt hàng", "Đơn vị tính", "Số lượng", "Đơn giá", "Thành tiền"
            }
        ));
        XUATHANGTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                XUATHANGTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(XUATHANGTable);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Đơn giá");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Thực hiện");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("Sửa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("Xoá");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("Thoát");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton5.setText("Làm mới");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Đơn vị tính");

        MaMHList.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MaMHList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chọn mã mặt hàng" }));
        MaMHList.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                MaMHListPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(MaPhieuXuatField, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                    .addComponent(SLField)
                    .addComponent(TotalField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DonViField)
                    .addComponent(PriceField)
                    .addComponent(MaMHList, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MaPhieuXuatField, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SLField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TotalField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MaMHList))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DonViField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //thực hiện xuất hàng
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String maphieuxuat, mh, dvtinh, soluong, price, total;      
        maphieuxuat = MaPhieuXuatField.getText();
        mh = MaMHList.getSelectedItem().toString();
        dvtinh = DonViField.getText();
        soluong = SLField.getText();
        price = PriceField.getText();
        total = TotalField.getText();
        
        TotalField.setEnabled(false);
        if (mh.equals("")         ||
            dvtinh.equals("")     ||
            soluong.equals("")   ) {
            JOptionPane.showMessageDialog(this,"Vui lòng nhập đầy đủ thông tin",
                "Thông báo",JOptionPane.ERROR_MESSAGE);
        
        } else {           
            try {
                PriceField.requestFocusInWindow();
                
           
                ps = con.prepareStatement("INSERT INTO CHITIETXUATHANG(MaPhieuXuat, MaMatHang, DonViTinh, SoLuong, DonGia, ThanhTien) "
                        + "values(?,?,?,?,?,?) ");
                
                
                ps.setString(1,maphieuxuat);
                ps.setString(2,mh);
                ps.setString(3,dvtinh);
                ps.setString(4,soluong);
                ps.setString(5,price);
                ps.setString(6,total);
               
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this,"Xuất hàng xong!","Đại lý",JOptionPane.INFORMATION_MESSAGE); 
                
                MaMHList.removeAllItems();
                
                
                
                MaMHList.setSelectedIndex(-1);
                DonViField.setText("");
                SLField.setText("");
                PriceField.setText("");
                TotalField.setText("");
                User_load();
                loadchitiet();
            } catch (SQLException ex) {
                Logger.getLogger(DAILYDOC.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this,"Phiếu này không tồn tại!\nBạn đã lưu phiếu chưa?","Phiếu xuất hàng",JOptionPane.ERROR_MESSAGE);
            }
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    //thao tác trên bảng
    private void XUATHANGTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XUATHANGTableMouseClicked
        d = (DefaultTableModel)XUATHANGTable.getModel();
        int selectIndex = XUATHANGTable.getSelectedRow();        
        MaPhieuXuatField.setText(d.getValueAt(selectIndex, 0).toString());
        MaMHList.setSelectedItem(d.getValueAt(selectIndex, 1).toString());
        DonViField.setText(d.getValueAt(selectIndex, 2).toString());
        SLField.setText(d.getValueAt(selectIndex, 3).toString());
        PriceField.setText(d.getValueAt(selectIndex, 4).toString());
        TotalField.setText(d.getValueAt(selectIndex, 5).toString());
   
        jButton1.setEnabled(false);
        MaMHList.setEnabled(false);
    }//GEN-LAST:event_XUATHANGTableMouseClicked
    //sửa phiếu thu tiền
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String maphieuxuat, mh, dvtinh, soluong, price, total;
        
        dvtinh = DonViField.getText();
        soluong = SLField.getText();
        price = PriceField.getText();
        total = TotalField.getText();      
            try {
                d = (DefaultTableModel)XUATHANGTable.getModel();
                int selectIndex = XUATHANGTable.getSelectedRow(); 
                maphieuxuat = d.getValueAt(selectIndex, 0).toString();
                mh = d.getValueAt(selectIndex, 1).toString();
                ps = con.prepareStatement("UPDATE CHITIETXUATHANG SET DonViTinh = ?, SoLuong = ?, DonGia = ?, ThanhTien = ? "
                        + "WHERE MaPhieuXuat = ? AND MaMatHang = ? ");
                              
                ps.setString(1,dvtinh);
                ps.setString(2,soluong);
                ps.setString(3,price);
                ps.setString(4,total);              
                ps.setString(5,maphieuxuat);
                ps.setString(6,mh);
                ps.executeUpdate();
                
                JOptionPane.showMessageDialog(this,"Chi tiết xuất hàng đã thay đổi!","Đại lý",JOptionPane.INFORMATION_MESSAGE); 
                jButton1.setEnabled(true);
                MaMHList.setEnabled(true);
                MaMHList.removeAllItems();
            
                MaMHList.setSelectedIndex(0);
                DonViField.setText("");
                SLField.setText("");
                PriceField.setText("");
                TotalField.setText("");
                User_load();
                loadchitiet();
            } catch (SQLException ex) {
                Logger.getLogger(DAILYDOC.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    //xoá phiếu xuất hàng
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         try {
                d = (DefaultTableModel)XUATHANGTable.getModel();
                int selectIndex = XUATHANGTable.getSelectedRow(); 
                String maphieuxuat = d.getValueAt(selectIndex, 0).toString();
                String mh = d.getValueAt(selectIndex, 1).toString();
                ps = con.prepareStatement("DELETE FROM CHITIETXUATHANG WHERE MaPhieuXuat = ? AND MaMatHang = ?");
                ps.setString(1,maphieuxuat);
                ps.setString(2,mh);
                ps.executeUpdate();
                
                JOptionPane.showMessageDialog(this,"Đã xoá mặt hàng trong phiếu!","Đại lý",JOptionPane.INFORMATION_MESSAGE); 
                jButton1.setEnabled(true);
                MaMHList.setEnabled(true);                             
                MaMHList.removeAllItems();
            
                MaMHList.setSelectedIndex(0);
                DonViField.setText("");
                SLField.setText("");
                PriceField.setText("");
                TotalField.setText("");               
                User_load();
                loadchitiet();
            } catch (SQLException ex) {
                Logger.getLogger(DAILYDOC.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed
    //làm mới
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        MaMHList.removeAllItems();
        jButton1.setEnabled(true);      
        SLField.setText("");
        TotalField.setText("");
        DonViField.setText("");
        PriceField.setText("");
        User_load();
        MaMHList.setSelectedIndex(0);
        loadchitiet();
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       this.dispose();
       
    }//GEN-LAST:event_jButton4ActionPerformed
    //hiện đơn giá khi chọn mã mặt hàng
    private void MaMHListPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_MaMHListPopupMenuWillBecomeInvisible
        String mh = MaMHList.getSelectedItem().toString();
        try {
            ps = con.prepareStatement("SELECT DonGia FROM MATHANG WHERE MaMatHang = ? ");
            ps.setString(1, mh);
            rs = ps.executeQuery();
            if (rs.next()) {
                String price = rs.getString("DonGia");
                int defprice  = Integer.parseInt(price);
                PriceField.setText(String.valueOf(defprice));
            }
        } catch (SQLException ex) {
            Logger.getLogger(ChiTietXuatHang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_MaMHListPopupMenuWillBecomeInvisible

    private void SLFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SLFieldKeyReleased
        String soluong = SLField.getText();
        String price = PriceField.getText();
        int sl = Integer.parseInt(soluong);
        int selprice  = Integer.parseInt(price);
        int getTotal = sl * selprice;
        TotalField.setText(String.valueOf(getTotal));
    }//GEN-LAST:event_SLFieldKeyReleased

    /**
     * @param args the command line arguments
     */
    public void User_load() {
        
        MaPhieuXuatField.setText(PhieuXuatHang.MaPhieuXuatField.getText());
        MaPhieuXuatField.setEditable(false);
        MaMHList.removeAllItems();
        MaMHList.addItem("Chọn mã mặt hàng");
        TotalField.setEditable(false);
        PriceField.setEditable(false);
        
        //danh sách mã mặt hàng
        try {
            ps1 = con.prepareStatement("SELECT MaMatHang FROM MATHANG");
            rs1 = ps1.executeQuery();
            while (rs1.next()) {
               String type = rs1.getString("MaMatHang");
               MaMHList.addItem(type);
            }
        } catch (SQLException ex) {
            Logger.getLogger(DAILYDOC.class.getName()).log(Level.SEVERE, null, ex);
        }        
      
    }
    public void loadchitiet() {
        int c; 
        String maphieuxuat = MaPhieuXuatField.getText();
        try {           
            ps2 = con.prepareStatement("SELECT * FROM CHITIETXUATHANG WHERE MaPhieuXuat = ? ");
            ps2.setString(1, maphieuxuat);
            rs2 = ps2.executeQuery();
            
            ResultSetMetaData rad = rs2.getMetaData();
            c = rad.getColumnCount();
            
            d = (DefaultTableModel)XUATHANGTable.getModel();
            d.setRowCount(0);
            
            while (rs2.next()) {
                Vector v2 = new Vector();
                for (int i = 1; i <= c; i++) {
                    v2.add(rs2.getString("MaPhieuXuat"));
                    v2.add(rs2.getString("MaMatHang"));
                    v2.add(rs2.getString("DonViTinh"));
                    v2.add(rs2.getString("SoLuong"));
                    v2.add(rs2.getString("DonGia"));
                    v2.add(rs2.getString("ThanhTien"));   
                }
                d.addRow(v2);
            }
             d.fireTableDataChanged();
            
        } catch (SQLException ex) {
            Logger.getLogger(DAILYDOC.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChiTietXuatHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChiTietXuatHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChiTietXuatHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChiTietXuatHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ChiTietXuatHang xh = new ChiTietXuatHang();
                xh.setVisible(true);
                xh.setResizable(false);
                xh.setTitle("Phiếu xuất hàng");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DonViField;
    private javax.swing.JComboBox<String> MaMHList;
    private javax.swing.JTextField MaPhieuXuatField;
    private javax.swing.JTextField PriceField;
    private javax.swing.JTextField SLField;
    private javax.swing.JTextField TotalField;
    private javax.swing.JTable XUATHANGTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
