/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nhom9.quanlidaily;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author honkaiwaifu
 */
public class ThuTien extends javax.swing.JFrame {
    Connection con = NewConnection.getConnection();
    PreparedStatement ps, ps1;
    ResultSet rs;
    DefaultTableModel d;
    /**
     * Creates new form ThuTien
     */
    public ThuTien() {
        initComponents();
        User_load();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        MaPhieuThuField = new javax.swing.JTextField();
        TelField = new javax.swing.JTextField();
        AddrField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        THUTIENTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        EmailField = new javax.swing.JTextField();
        TienThuField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        DatePicker = new org.jdesktop.swingx.JXDatePicker();
        MaDaiLyList = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        NameField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(230, 34, 34));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("PHIẾU THU TIỀN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Mã phiếu thu");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Mã đại lý");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Điện Thoại");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Địa chỉ");

        THUTIENTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã phiếu thu", "Mã đại lý", "Điện thoại", "Địa chỉ", "Email", "Ngày thu tiền", "Số tiền thu"
            }
        ));
        THUTIENTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                THUTIENTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(THUTIENTable);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Email");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Ngày thu tiền");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Số tiền thu");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Thực hiện");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("Sửa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("Xoá");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("Thoát");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton5.setText("Xoá nhập");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        MaDaiLyList.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MaDaiLyList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chọn mã đại lý" }));
        MaDaiLyList.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                MaDaiLyListPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Tên đại lý");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(MaPhieuThuField, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                    .addComponent(TelField)
                    .addComponent(AddrField)
                    .addComponent(NameField, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TienThuField)
                            .addComponent(DatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MaDaiLyList, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MaDaiLyList, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MaPhieuThuField, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NameField, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TelField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddrField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(EmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TienThuField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //thực hiện thu tiền
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String maphieuthu, madaily, tel, addr, email, date, tienthu;
        maphieuthu = MaPhieuThuField.getText();
        madaily = MaDaiLyList.getSelectedItem().toString();
        tel = TelField.getText();
        addr = AddrField.getText();
        email = EmailField.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        date = sdf.format(DatePicker.getDate());
        tienthu = TienThuField.getText();
        if (maphieuthu.equals("") || 
            madaily.equals("")    || 
            tel.equals("")        ||
            addr.equals("")       ||
            email.equals("")      ||
            date.equals("")       ||
            tienthu.equals("") ) {
            JOptionPane.showMessageDialog(this,"Vui lòng nhập đầy đủ thông tin",
                "Thông báo",JOptionPane.ERROR_MESSAGE);
        
        } else {           
            try {
                int deftienthu = Integer.parseInt(tienthu);
                ps = con.prepareStatement("SELECT * FROM DAILY");
                rs = ps.executeQuery();
                if (rs.next()) {
                    int deftienno = Integer.parseInt(rs.getString("TienNo"));
                    if (deftienthu < deftienno || deftienno == 0) {
                        ps1 = con.prepareStatement("INSERT INTO PHIEUTHUTIEN(MaPhieuThu, MaDaiLy, DienThoai, DiaChi, Email, NgayThuTien, SoTienThu) "
                                + "values(?,?,?,?,?,?,?) ");
                        ps1.setString(1,maphieuthu);
                        ps1.setString(2,madaily);
                        ps1.setString(3,tel);
                        ps1.setString(4,addr);
                        ps1.setString(5,email);
                        ps1.setString(6,date);
                        ps1.setString(7,tienthu);
                        ps1.executeUpdate();
                        JOptionPane.showMessageDialog(this,"Thu tiền xong","Đại lý",JOptionPane.INFORMATION_MESSAGE);               
                        MaPhieuThuField.setText("");
                        MaDaiLyList.setSelectedIndex(0);
                        TelField.setText("");
                        AddrField.setText("");
                        EmailField.setText("");
                        TienThuField.setText("");
                        User_load();
                    } else  {
                        JOptionPane.showMessageDialog(this,"Số tiền thu vượt quá số tiền nợ","Đại lý",JOptionPane.ERROR_MESSAGE); 
                        
                    }
              }
            } catch (SQLException ex) {
                Logger.getLogger(DAILYDOC.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void THUTIENTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_THUTIENTableMouseClicked
        d = (DefaultTableModel)THUTIENTable.getModel();
        int selectIndex = THUTIENTable.getSelectedRow();        
        MaPhieuThuField.setText(d.getValueAt(selectIndex, 0).toString());
        MaDaiLyList.setSelectedItem(d.getValueAt(selectIndex, 1).toString());
        TelField.setText(d.getValueAt(selectIndex, 2).toString());
        AddrField.setText(d.getValueAt(selectIndex, 3).toString());
        EmailField.setText(d.getValueAt(selectIndex, 4).toString());
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");       
        try {
            DatePicker.setDate(sdf.parse(d.getValueAt(selectIndex, 5).toString()));
        } catch (ParseException ex) {
            Logger.getLogger(DAILYDOC.class.getName()).log(Level.SEVERE, null, ex);
        }
        TienThuField.setText(d.getValueAt(selectIndex, 6).toString());
        String madl = MaDaiLyList.getSelectedItem().toString();
        try {
            ps = con.prepareStatement("SELECT TenDaiLy FROM DAILY WHERE MaDaiLy = ? ");
            ps.setString(1, madl);
            rs = ps.executeQuery();
            if (rs.next()) {
                String name = rs.getString("TenDaiLy");
                NameField.setText(String.valueOf(name));
            }
        } catch (SQLException ex) {
            Logger.getLogger(PhieuXuatHang.class.getName()).log(Level.SEVERE, null, ex);
        }
        MaPhieuThuField.setEnabled(false);
        jButton1.setEnabled(false);

    }//GEN-LAST:event_THUTIENTableMouseClicked
    //sửa phiếu thu tiền
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String maphieuthu, madaily, tel, addr, email, date, tienthu;
        maphieuthu = MaPhieuThuField.getText();
        madaily = MaDaiLyList.getSelectedItem().toString();
        tel = TelField.getText();
        addr = AddrField.getText();
        email = EmailField.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        date = sdf.format(DatePicker.getDate());
        tienthu = TienThuField.getText();
            try {
                d = (DefaultTableModel)THUTIENTable.getModel();
                int selectIndex = THUTIENTable.getSelectedRow(); 
                maphieuthu = d.getValueAt(selectIndex, 0).toString();
                int deftienthu = Integer.parseInt(tienthu);
                ps = con.prepareStatement("SELECT * FROM DAILY");
                rs = ps.executeQuery();
                if (rs.next()) {
                    int deftienno = Integer.parseInt(rs.getString("TienNo"));
                    if (deftienthu < deftienno || deftienno == 0) {
                        ps1 = con.prepareStatement("UPDATE PHIEUTHUTIEN SET MaDaiLy = ?, DienThoai = ?, DiaChi = ?, Email = ?, NgayThuTien = ?, SoTienThu = ? "
                                + "WHERE MaPhieuThu = ? ");

                        ps1.setString(1,madaily);
                        ps1.setString(2,tel);
                        ps1.setString(3,addr);
                        ps1.setString(4,email);
                        ps1.setString(5,date);
                        ps1.setString(6,tienthu);
                        ps1.setString(7,maphieuthu);
                        ps1.executeUpdate();

                        JOptionPane.showMessageDialog(this,"Phiếu thu tiền đã thay đổi!","Đại lý",JOptionPane.INFORMATION_MESSAGE); 
                        jButton1.setEnabled(true);
                        MaPhieuThuField.setEnabled(true);

                        MaPhieuThuField.setText("");
                        MaDaiLyList.setSelectedIndex(0);
                        TelField.setText("");
                        AddrField.setText("");
                        EmailField.setText("");
                        TienThuField.setText("");
                        User_load();
                    } else  {
                        JOptionPane.showMessageDialog(this,"Số tiền thu vượt quá số tiền nợ","Đại lý",JOptionPane.ERROR_MESSAGE);
                        
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(DAILYDOC.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    //xoá phiếu thu tiền
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         try {
                d = (DefaultTableModel)THUTIENTable.getModel();
                int selectIndex = THUTIENTable.getSelectedRow(); 
                String maphieuthu = d.getValueAt(selectIndex, 0).toString();
                ps = con.prepareStatement("DELETE FROM PHIEUTHUTIEN WHERE MaPhieuThu = ?");
                ps.setString(1,maphieuthu);
                ps.executeUpdate();
                
                JOptionPane.showMessageDialog(this,"Đã xoá phiếu thu tiền!","Đại lý",JOptionPane.INFORMATION_MESSAGE); 
                jButton1.setEnabled(true);
                MaPhieuThuField.setEnabled(true);
            
                MaPhieuThuField.setText("");
                MaDaiLyList.setSelectedIndex(0);
                TelField.setText("");
                AddrField.setText("");
                EmailField.setText("");
                TienThuField.setText("");
                User_load();
            } catch (SQLException ex) {
                Logger.getLogger(DAILYDOC.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed
    //xoá dữ liệu đã nhập trong fieldtext
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jButton1.setEnabled(true);
        MaPhieuThuField.setEnabled(true);           
        MaPhieuThuField.setText("");
        MaDaiLyList.setSelectedIndex(0);
        TelField.setText("");
        AddrField.setText("");
        EmailField.setText("");
        TienThuField.setText("");
        User_load();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed
    //tự động điền sau khi chọn mã đại lý
    private void MaDaiLyListPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_MaDaiLyListPopupMenuWillBecomeInvisible
       String madl = MaDaiLyList.getSelectedItem().toString();
        try {
            ps = con.prepareStatement("SELECT * FROM DAILY WHERE MaDaiLy = ? ");
            ps.setString(1, madl);
            rs = ps.executeQuery();
            if (rs.next()) {
                String name = rs.getString("TenDaiLy");
                String tel  = rs.getString("DienThoai");
                String addr = rs.getString("DiaChi");
                String email = rs.getString("Email");
                NameField.setText(String.valueOf(name));
                TelField.setText(String.valueOf(tel));
                AddrField.setText(String.valueOf(addr));
                EmailField.setText(String.valueOf(email));
            }
        } catch (SQLException ex) {
            Logger.getLogger(PhieuXuatHang.class.getName()).log(Level.SEVERE, null, ex);
        }                        
    }//GEN-LAST:event_MaDaiLyListPopupMenuWillBecomeInvisible

    /**
     * @param args the command line arguments
     */
    public void User_load() {
        int c;
        NameField.setEditable(false);
        TelField.setEditable(false);
        AddrField.setEditable(false);
        EmailField.setEditable(false);
        MaDaiLyList.removeAllItems();
        MaDaiLyList.addItem("Chọn mã đại lý");
        //danh sách các mã đại lý
        try {
            ps = con.prepareStatement("SELECT MaDaiLy FROM DaiLy");
            rs = ps.executeQuery();
            while (rs.next()) {
               String maDaiLy = rs.getString("MaDaiLy");
               MaDaiLyList.addItem(maDaiLy);
            }
        } catch (SQLException ex) {
            Logger.getLogger(PhieuXuatHang.class.getName()).log(Level.SEVERE, null, ex);
        }
        
       try {
            ps = con.prepareStatement("SELECT MaPhieuThu, DAILY.MaDaiLy, PHIEUTHUTIEN.DienThoai, PHIEUTHUTIEN.DiaChi, PHIEUTHUTIEN.Email, NgayThuTien, SoTienThu "
                    + "FROM PHIEUTHUTIEN, DAILY WHERE PHIEUTHUTIEN.MaDaiLy = DAILY.MaDaiLy");
            rs = ps.executeQuery();
            
            ResultSetMetaData rad = rs.getMetaData();
            c = rad.getColumnCount();
            
            d = (DefaultTableModel)THUTIENTable.getModel();
            d.setRowCount(0);
            
            while (rs.next()) {
                Vector v2 = new Vector();
                for (int i = 1; i <= c; i++) {
                    v2.add(rs.getString("MaPhieuThu"));
                    v2.add(rs.getString("MaDaiLy"));
                    v2.add(rs.getString("DienThoai"));
                    v2.add(rs.getString("DiaChi"));
                    v2.add(rs.getString("Email"));
                    v2.add(rs.getString("NgayThuTien"));
                    v2.add(rs.getString("SoTienThu"));                    
                }
                d.addRow(v2);
            }
             d.fireTableDataChanged();
        } catch (SQLException ex) {
            Logger.getLogger(DAILYDOC.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThuTien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThuTien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThuTien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThuTien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ThuTien t = new ThuTien();
                t.setVisible(true);
                t.setResizable(false);
                t.setTitle("Phiếu thu tiền");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddrField;
    private org.jdesktop.swingx.JXDatePicker DatePicker;
    private javax.swing.JTextField EmailField;
    private javax.swing.JComboBox<String> MaDaiLyList;
    private javax.swing.JTextField MaPhieuThuField;
    private javax.swing.JTextField NameField;
    private javax.swing.JTable THUTIENTable;
    private javax.swing.JTextField TelField;
    private javax.swing.JTextField TienThuField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
